### ISSUE TITLE
Niepoprawne wyświetlanie polskich znaków

### ISSUE THREAD

**Issue by DawidFurs** [RafalGruszka/ZaawansowaneProgramowanie_PracaZaliczeniowa#8]
Złe znaki w :
powierzchnia_lodygi_ponizej_pierscienia: g?adka
rodzaj_oslony: cz?ciowa
rodzaj_pierscienia: du?y
srodowisko: le?ne, nieu?ytki

**Comment by RafalGruszka** [comment]
All mistakes corrected and missing polish translation added.
